#!/bin/bash

set -u


function get_config
{
    local varname="$1"
    python -c "from local_config import * ; print ${varname}"
}


./check_config_files || exit

SLAVEDIR=~/.buildbot_slave

MASTER_HOST=$(get_config buildbot_hostname)
if [[ $MASTER_HOST == $(hostname) ]]; then
    MASTER_HOST=localhost
fi
MASTER_PORT=$(get_config slave_port)

MACOSX_VERSION=$(sw_vers -productVersion | grep -Eo '^[0-9]+(\.[0-9]+)?')
SLAVE_NAME="MacOSX-${MACOSX_VERSION}-x86_64"
SLAVE_PASS=$(get_config slave_pass)

rm -Rf $SLAVEDIR
buildbot create-slave --umask=022 $SLAVEDIR \
    $MASTER_HOST:$MASTER_PORT \
    $SLAVE_NAME $SLAVE_PASS

get_config buildbot_admin > $SLAVEDIR/info/admin
system_profiler SPHardwareDataType SPSoftwareDataType > $SLAVEDIR/info/host

buildbot start $SLAVEDIR
