#!/bin/bash

set -u


./check_config_files || exit

MASTERDIR=~/.buildbot_master

rm -Rf $MASTERDIR
buildbot create-master --relocatable $MASTERDIR
cp master.cfg local_config.py local_passwords.py $MASTERDIR

#buildbot start $MASTERDIR

PLIST=org.mworks-project.buildbot.master.plist
PLISTDIR=~/Library/LaunchAgents
mkdir -p $PLISTDIR
cp $PLIST $PLISTDIR

launchctl load $PLISTDIR/$PLIST
