#!/usr/bin/env -S "/Library/Application\_Support/MWorks/MWEL/.python"

import sys
sys.path.insert(0, '/Library/Application Support/MWorks/MWEL')

import mwel


if __name__ == '__main__':
    sys.exit(mwel.toxml())
