repository_base_url = 'git://github.com/mworks-project/' 
installer_destination_path = '/home/coxlab/webapps/public/'
project_url = 'http://monkeyworks-project.github.com'
buildbot_hostname = 'monkeyworks.coxlab.org'
installer_download_base_url = 'http://public.coxlab.org/mw/'
