repository_base_url = 'git://github.com/dicarlolab-mworks/' 
installer_destination_path = '/Library/WebServer/Documents/mw/'
project_url = 'http://github.com/dicarlolab-mworks'
buildbot_hostname = 'dicarlo-mwdev.mit.edu'
installer_download_base_url = 'http://dicarlo-mwdev.mit.edu/mw/'
